export const GLOBAL = {
  SET_LANGUAGE: "SET_LANGUAGE",
  SET_SEARCH: "SET_SEARCH",
  SET_ROUTE: "SET_ROUTE",
};

export const MENUITEM={
  SET_MENUITEM_COLLECTION:"SET_ITEM_COLLECTION",
  SET_MENUITEM_CATEGORY:"SET_ITEM_CATEGORY",
  SET_MENUITEM_SUBCATEGORY:"SET_ITEM_SUBCATEGORY",
  REMOVE_MENUITEM_CATEGORY:"SET_ITEM_SUBCATEGORY",
  REMOVE_MENUITEM_SUBCATEGORY:"REMOVE_ITEM_SUBCATEGORY",
  RESET_MENUITEM:"RESET_MENUITEM"
}

export const USER = {
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
};

export const PAGE = {
  SET_PAGE_NUMBER: "PAGE_NUMBER",
  SET_NUMBER_ITEMS_PER_PAGE: "NUMBER_ITEMS",
};

export const MENU = {
  SET_MENU: "SET_MAIN_MENU",
};
