module.exports={
    INVITATIONS:'/api/invitations',
    CARDS:'/api/cards',
    USERS:'/api/users',
    NEW_USER:'/api/users/new_user',
    TAGS:'/api/tags',
    RELATE:'/api/relate',
    COLLECTIONS:'/api/collections',
    CATEGORIES:'/api/categories',
    SUB_CATEGORIES:'/api/sub-categories',
    SUB_CATEGORIES_CHILD:'/api/sub-items',
    SIGNUP:'/api/account/signup',
    LOGIN:'/api/account/login',
}